### ISSUE TITLE
SSH into Drobo

### ISSUE THREAD

**Issue by dipeshgreenman** [droboports/openssh#8]
Hello,

I would like to SSH into Drobo to see different files, who is logged in etc...
We have 2 Drobo's connected using LAN both B800fs.

One of my previous thread:
https://support.drobo.com/app/account/qu..._id/252495

Steps I have replicated: 
I have used this website (http://www.drobospace.com/forums/showthr...tid=141632
) to solve my problem.
For this I guess I need to download OpenSSH via (http://www.droboports.com/app-repository/openssh/), I will consider having root access so I will visit this (https://github.com/droboports/sudo) and run following commands on my terminal:
"git clone https://github.com/droboports/sudo.git
cd sudo
./build.sh"

This is the output i get:
"UserA$ git clone https://github.com/droboports/sudo.git
Cloning into 'sudo'...
remote: Counting objects: 40, done.
remote: Total 40 (delta 0), reused 0 (delta 0), pack-reused 40
Unpacking objects: 100% (40/40), done.
Checking connectivity... done.
ip-:sudo dipesh$ cd sudo
ip-:sudo dipesh$ ./build.sh
++ date +%Y-%m-%d_%H-%M-%S
- timestamp=2016-03-24_12-10-22
- logfile=logfile_2016-03-24_12-10-22.txt
  ./build.sh: line 18: @: unbound variable"

Now its time to SSH into Drobo. So I run

UserA$ ssh root@192.168.1.5
ssh: connect to host 192.168.1.5 port 22: Connection refused

Is there something I am missing if yes could help please (may be replication steps like me)

Regards,
Dipesh

**Comment by ricardopadilha** [comment]
You can download a B800fs compatible version of OpenSSH here: https://github.com/droboports/openssh/releases/tag/v7.1p2-fs

You'll have have root access by default, so no need for sudo.

Your compilation is not working because you are not using a cross-compiler VM, as indicated here: https://github.com/droboports/droboports.github.io/wiki/Setting-up-a-VM

Keep in mind that github issues in this project are restricted to problems with the build scripts. Please direct questions about using DroboApps to the DroboSpace forums (http://www.drobospace.com/forums/), or the respective app websites.

**Comment by dipesh010** [comment]
Hi ricardopadilha,

I have downloaded VM 866MB file from:
https://github.com/droboports/droboports.github.io/wiki/Setting-up-a-VM

Started the VM and i get prompt with drobocompiler login (username + password).

I have tried my Drobo admin username password but its keep refusing (Login incorrect). Where do I get these username + password from?



![screen shot 2016-03-29 at 13 10 44](https://cloud.githubusercontent.com/assets/7958366/14107511/92f8783c-f5b0-11e5-9ac2-e00cefadc09c.png)
